### ISSUE TITLE
Codeigniter version

### ISSUE THREAD

**Issue by ronlinet** [CIFullCalendar/cifullcalendar#2]
Does this code run with Codeigniter 2.1 ?

**Comment by SirDre** [comment]
Not sure because I did not degrade to run test.

Please ensure that you update CI and the links are reference guides to do so: 

See here:
https://github.com/bcit-ci/CodeIgniter/blob/b4d719dc7fb3b010b53c09e7e82f979abf731ff9/user_guide_src/source/installation/upgrade_211.rst

Other Versions:
https://github.com/bcit-ci/CodeIgniter/tree/b4d719dc7fb3b010b53c09e7e82f979abf731ff9/user_guide_src/source/installation
